const NEW_USER_REGISTRATION = "NEW_USER_REGISTRATION",
  EDIT_PROFILE_SAVE = "EDIT_PROFILE_SAVE",
  SET_ACTIVE_ZODIAC = "SET_ACTIVE_ZODIAC",
  SET_COMPATIBILITY = "SET_COMPATIBILITY";

export {
  NEW_USER_REGISTRATION,
  SET_COMPATIBILITY,
  SET_ACTIVE_ZODIAC,
  EDIT_PROFILE_SAVE,
};
